# Generated by Django 4.2.19 on 2025-02-16 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snake', '0002_score'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Score',
        ),
    ]
